### ISSUE TITLE
hunspell не збирається

### ISSUE THREAD

**Issue by eugene55** [brown-uk/dict_uk#243]
Трейс:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method putAll() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Hunspell$_run_closure3$_closure16.doCall(Hunspell.groovy:40)
```
Після накладання цього патчу проєкт зібрати можливо, але я не впевнений щодо результату:
```
--- a/distr/hunspell/src/main/groovy/Hunspell.groovy    2020-06-21 17:30:17.000000000 +0000
+++ b/distr/hunspell/src/main/groovy/Hunspell.groovy    2020-06-23 18:44:08.080812476 +0000
@@ -36,7 +36,7 @@

 affixMap.each { flag, affixGroupMap ->
     reMapFlags.each { k,v ->
-       if( flag.startsWith(k) ) {
+       if( flag.startsWith(k) && flag.replace(k, v) in affixMap.keySet()) {
                affixMap[ flag.replace(k, v) ].putAll(affixGroupMap)
        }
     }
```

**Comment by arysin** [comment]
Там ще треба трішки попрацювати над кличним для неістот, але наразі має збиратися.

**Comment by eugene55** [comment]
Я спробував зібрати, коли оновлював свій пакунок aur.archlinux.org/packages/hunspell-uk
Виявилося, що у релізі немає файлів для hunspell
Якщо у наступному релізі буде hunspell, то це буде чудово.

**Comment by arysin** [comment]
Так, як раз збирався викласти файли hunspell

**Comment by arysin** [comment]
Виклав.

**Comment by eugene55** [comment]
Дякую за співпрацю
