### ISSUE TITLE
./gradlew expand fails on Mac Catalina 10.15.7 (19H2)

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [brown-uk/dict_uk#287]
```
> Task :autogen FAILED
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/dict_uk/tools/Autogen has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by arysin** [comment]
Hey, I wonder if you have different versions of Java or it was updated recently?
You can try to do ./gradlew clean first and/or maybe ./gradlew --stop (to restart gradle daemon if it's up)

**Comment by BarnabasSzabolcs** [comment]
Hey Arysin, thanks for the quick answer!

`java -version` returns

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by arysin** [comment]
Hey, you can try to install JDK11, technically jdk 8 reached end of life a year ago.
It looks like Autogen class was compiled by jdk 11 for some reason and current java 8 fails to parse it.
You can also try to delete .gradle/ and build/ folders manually. 
P.S. oh, I just realized I set java version 11 in the gadle so that's the best path to go

**Comment by BarnabasSzabolcs** [comment]
Ok, it seems the following has to be done for mac:
```
brew install java11
JAVA_HOME=
./gradlew expand
```
